name: CI

on:
  pull_request:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  lint:
    name: linting and formatting

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: run linting/formatting
        run: |
          python -Im pip install tox tox-ignore-env-name-mismatch
          python -Im tox run -e format,lint

  test:
    name: tests (pytest on 3.10)

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: prepare python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: run tests via tox
        run: |
          python -Im pip install tox tox-ignore-env-name-mismatch
          python -Im tox run -e py310-test

  # ensure everything required passed
  required-checks-pass:
    if: always()

    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:
      - name: check CI success or failure
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
